{"_default": {"1": {"app_name": "test1", "docker_image": "digitalocean/flask-helloworld", "dashboard_url": "/dashboard/test1", "app_url": "http://test1.hoster.local", "user_id": "admin"}}, "instances": {"1": {"provisioned": false, "provisioning": false, "docker_image": "digitalocean/flask-helloworld", "user_id": "admin", "machine_url": "http://192.168.196.125", "error": "HTTPConnectionPool(host='192.168.196.125', port=8080): Max retries exceeded with url: /build-from-hub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee3419d1c0>: Failed to establish a new connection: [Errno 113] No route to host'))"}}}